---
# tasks file for ansible_auto_update

- name: Update repos and cache
  apt: 
    update_cache: yes 
    cache_valid_time: 3600

- name: Upgrade the OS
  apt: 
    upgrade: dist

- name: Install unattended-upgrades tools
  apt:
    name:
      - unattended-upgrades
    state: present
    update_cache: yes

- name: Configure auto upgrades
  template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644 
  notify:
    - Restart unattended upgrades

- name: Enable automatic updates and upgrades
  replace:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    after: 'Unattended-Upgrade::Allowed-Origins {'
    before: '};'
    replace: '{{ item.replace }}'
    regexp: '{{ item.regexp }}'
  with_items:
    - {regexp: '\/\/\s*"\${distro_id}:\${distro_codename}";', replace: '        "${distro_id}:${distro_codename}";'}
    - {regexp: '\/\/\s*"\${distro_id}:\${distro_codename}-security";', replace: '        "${distro_id}:${distro_codename}-security";'}
    - {regexp: '\/\/\s*"\${distro_id}ESMApps:\${distro_codename}-apps-security";', replace: '        "${distro_id}ESMApps:${distro_codename}-apps-security";'}
    - {regexp: '\/\/\s*"\${distro_id}ESM:\${distro_codename}-infra-security";', replace: '        "${distro_id}ESM:${distro_codename}-infra-security";'}
    - {regexp: '\/\/\s*"\${distro_id}:\${distro_codename}-updates";', replace: '        "${distro_id}:${distro_codename}-updates";'}
  notify:
    - Restart unattended upgrades

